services:
  - type: web
    name: comment-system
    env: php
    buildCommand: "composer install"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    plan: free
    region: oregon
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
